//! Zero-copy, mmap-backed readers for `.cch-struct` and `.cch-metric` bundles.
//!
//! [`CchBundle`] opens a `.cch-struct` file and exposes its arrays as
//! borrowed slices via [`CchView`]; no data is copied — the OS page cache
//! backs the slices directly. Similarly, [`MetricBundle`] opens a
//! `.cch-metric-*` file and exposes forward + backward weight arrays via
//! [`MetricView`].
//!
//! The bundle format is fixed: `.cch-struct` uses magic `CCH_STRC` (version 1)
//! and `.cch-metric` uses magic `CCH_METR` (version 1). Any existing corpus of
//! 316 GB bundles depends on this exact layout; do not change it.
//!
//! Ported from `native/routing-core/src/cch_mmap.rs` in rapidonkey
//! (`CchBundleMmap` / `MetricBundleMmap` / `CchMmapView` / `MetricMmapView`).

/// `RoutingKit`'s `invalid_id` sentinel (`unsigned(-1)` in C++).
pub const INVALID_ID: u32 = u32::MAX;

/// Read-only view over the CCH fields needed for distance-matrix queries.
///
/// Holds borrowed slices — typically backed by mmap'd bundle pages
/// (zero-copy). The lifetime `'a` is tied to the [`CchBundle`] owner.
pub struct CchView<'a> {
    /// `rank[external_node_id]` → CCH-internal node id. Length = `node_count`.
    pub rank: &'a [u32],
    /// `elimination_tree_parent[v]` → parent of v in the elimination tree,
    /// or [`INVALID_ID`] for the root. Length = `node_count`.
    pub elimination_tree_parent: &'a [u32],
    /// CSR offsets for upward arcs. Length = `node_count` + 1.
    pub up_first_out: &'a [u32],
    /// Head endpoint of each upward arc. Length = `cch_arc_count`.
    pub up_head: &'a [u32],
    /// CSR offsets for downward arcs. Length = `node_count` + 1.
    pub down_first_out: &'a [u32],
    /// Head endpoint of each downward arc. Length = `cch_arc_count`.
    pub down_head: &'a [u32],
    /// Maps each downward arc index to its corresponding upward arc index.
    /// Length = `cch_arc_count`.
    pub down_to_up: &'a [u32],
}

impl CchView<'_> {
    /// Number of nodes. Derived from `rank.len()`.
    #[must_use]
    #[allow(clippy::cast_possible_truncation)] // node_count fits u32 (CCH limit)
    pub fn node_count(&self) -> u32 {
        self.rank.len() as u32
    }

    /// Number of CCH arcs (the contracted graph's arc count, NOT the input
    /// edge count). Derived from `up_head.len()`.
    #[must_use]
    #[allow(clippy::cast_possible_truncation)] // arc_count fits u32 (CCH limit)
    pub fn cch_arc_count(&self) -> u32 {
        self.up_head.len() as u32
    }
}

/// Read-only view over a single customized metric's forward + backward weight
/// arrays. Lifetime `'a` is tied to the [`MetricBundle`] owner.
pub struct MetricView<'a> {
    /// `forward[arc]` → shortcut weight for arc in the up→down direction.
    pub forward: &'a [u32],
    /// `backward[arc]` → shortcut weight for arc in the down→up direction.
    pub backward: &'a [u32],
}

// ---------------------------------------------------------------
// Mmap loader — zero-copy via memmap2
// ---------------------------------------------------------------

/// Mmap-backed owner for a `.cch-struct` bundle. Holds the [`memmap2::Mmap`]
/// alive for its lifetime; the slices in [`Self::view`] borrow into the mapped
/// region (zero-copy). Process heap allocation is just offset bookkeeping
/// (~48 bytes); the actual CCH data lives in the OS page cache and is shared
/// across processes that mmap the same file.
pub struct CchBundle {
    mmap: memmap2::Mmap,
    rank_off: usize,
    elim_off: usize,
    up_first_out_off: usize,
    up_head_off: usize,
    down_first_out_off: usize,
    down_head_off: usize,
    down_to_up_off: usize,
    node_count: usize,
    cch_arc_count: usize,
}

impl CchBundle {
    /// Open a `.cch-struct` bundle at `path`, memory-map it, and validate the
    /// header + section layout. Returns an error on I/O failure or a malformed
    /// bundle.
    ///
    /// # Errors
    ///
    /// Returns [`std::io::Error`] on I/O failure, bad magic, unsupported
    /// version, truncated sections, or unaligned section data.
    #[allow(clippy::cast_possible_truncation)] // bundle values fit usize (checked by section length guard)
    pub fn open(path: &std::path::Path) -> std::io::Result<Self> {
        const STRUCT_MAGIC: u64 = 0x4343_485F_5354_5243;

        let file = std::fs::File::open(path)?;
        // SAFETY: requires the underlying file not be modified while the
        // mapping is live. We open read-only; production artifacts are
        // immutable (regenerated by `cch-spike build-cch-bundles` — never
        // edited in place).
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        if mmap.len() < 40 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "bundle too small to contain header",
            ));
        }

        let bytes = &mmap[..];
        let magic = read_u64_le_at(bytes, 0);
        if magic != STRUCT_MAGIC {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "bad magic in {}: {magic:#x}, expected {STRUCT_MAGIC:#x}",
                    path.display()
                ),
            ));
        }
        let version = read_u32_le_at(bytes, 8);
        if version != 1 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("unsupported struct version {version}"),
            ));
        }
        let node_count = read_u64_le_at(bytes, 16) as usize;
        let cch_arc_count = read_u64_le_at(bytes, 24) as usize;
        let _input_arc_count = read_u64_le_at(bytes, 32) as usize;

        // Walk sections; capture offsets for the ones we need.
        let mut pos = 40usize;
        let mut data_off = |label: &str| -> std::io::Result<usize> {
            if pos + 8 > bytes.len() {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("truncated bundle at section '{label}'"),
                ));
            }
            let byte_length = read_u64_le_at(bytes, pos) as usize;
            pos += 8;
            let off = pos;
            pos += byte_length;
            if pos > bytes.len() {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("section '{label}' extends past end of mmap"),
                ));
            }
            Ok(off)
        };

        let _order_off = data_off("order")?;
        let rank_off = data_off("rank")?;
        let elim_off = data_off("elimination_tree_parent")?;
        let up_first_out_off = data_off("up_first_out")?;
        let up_head_off = data_off("up_head")?;
        let _up_tail_off = data_off("up_tail")?;
        let down_first_out_off = data_off("down_first_out")?;
        let down_head_off = data_off("down_head")?;
        let down_to_up_off = data_off("down_to_up")?;

        // Verify u32 alignment of the slices we'll hand out. Bundles
        // produced by the current writer should always be 4-byte aligned
        // (mmap base is page-aligned; each section starts after a u64
        // prefix + u32 vectors of bytes-length-multiple-of-4).
        let base = mmap.as_ptr() as usize;
        for (name, off) in [
            ("rank", rank_off),
            ("elimination_tree_parent", elim_off),
            ("up_first_out", up_first_out_off),
            ("up_head", up_head_off),
            ("down_first_out", down_first_out_off),
            ("down_head", down_head_off),
            ("down_to_up", down_to_up_off),
        ] {
            let addr = base + off;
            if addr % std::mem::align_of::<u32>() != 0 {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!(
                        "section '{name}' is not u32-aligned (offset {off}); \
                         bundle format would need padding or fall back to eager load"
                    ),
                ));
            }
        }

        Ok(CchBundle {
            mmap,
            rank_off,
            elim_off,
            up_first_out_off,
            up_head_off,
            down_first_out_off,
            down_head_off,
            down_to_up_off,
            node_count,
            cch_arc_count,
        })
    }

    /// Return a zero-copy view over the mmap'd CCH arrays.
    ///
    /// The returned [`CchView`] borrows from `self` — it cannot outlive the
    /// bundle.
    #[must_use]
    pub fn view(&self) -> CchView<'_> {
        // SAFETY: open() validated u32 alignment for each offset. The mmap
        // outlives the slices (lifetime tied to &self). The mapped region is
        // read-only and immutable for the lifetime of the Mmap. The alignment
        // check in open() ensures the cast_ptr_alignment requirement is met.
        #[allow(clippy::cast_ptr_alignment)] // alignment verified in open()
        unsafe {
            CchView {
                rank: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.rank_off).cast::<u32>(),
                    self.node_count,
                ),
                elimination_tree_parent: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.elim_off).cast::<u32>(),
                    self.node_count,
                ),
                up_first_out: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.up_first_out_off).cast::<u32>(),
                    self.node_count + 1,
                ),
                up_head: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.up_head_off).cast::<u32>(),
                    self.cch_arc_count,
                ),
                down_first_out: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.down_first_out_off).cast::<u32>(),
                    self.node_count + 1,
                ),
                down_head: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.down_head_off).cast::<u32>(),
                    self.cch_arc_count,
                ),
                down_to_up: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.down_to_up_off).cast::<u32>(),
                    self.cch_arc_count,
                ),
            }
        }
    }

    /// Number of nodes in the CCH.
    #[must_use]
    pub fn node_count(&self) -> usize {
        self.node_count
    }

    /// Number of CCH arcs.
    #[must_use]
    pub fn cch_arc_count(&self) -> usize {
        self.cch_arc_count
    }
}

/// Mmap-backed owner for a `.cch-metric-*` bundle.
pub struct MetricBundle {
    mmap: memmap2::Mmap,
    forward_off: usize,
    backward_off: usize,
    cch_arc_count: usize,
}

impl MetricBundle {
    /// Open a `.cch-metric` bundle at `path`, memory-map it, and validate the
    /// header + section layout.
    ///
    /// # Errors
    ///
    /// Returns [`std::io::Error`] on I/O failure, bad magic, unsupported
    /// version, truncated sections, or unaligned section data.
    #[allow(clippy::cast_possible_truncation)] // bundle values fit usize (checked by section length guard)
    pub fn open(path: &std::path::Path) -> std::io::Result<Self> {
        const METRIC_MAGIC: u64 = 0x4343_485F_4D45_5452;

        let file = std::fs::File::open(path)?;
        // SAFETY: requires the underlying file not be modified while the
        // mapping is live. We open read-only; production artifacts are
        // immutable.
        let mmap = unsafe { memmap2::Mmap::map(&file)? };
        if mmap.len() < 24 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "metric bundle too small",
            ));
        }
        let bytes = &mmap[..];
        let magic = read_u64_le_at(bytes, 0);
        if magic != METRIC_MAGIC {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("bad metric magic in {}: {magic:#x}", path.display()),
            ));
        }
        let version = read_u32_le_at(bytes, 8);
        if version != 1 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("unsupported metric version {version}"),
            ));
        }
        let cch_arc_count = read_u64_le_at(bytes, 16) as usize;

        // Header (24 bytes), then 2 sections each [u64 byte_length][bytes...].
        let mut pos = 24usize;
        let forward_len = read_u64_le_at(bytes, pos) as usize;
        pos += 8;
        let forward_off = pos;
        pos += forward_len;
        let backward_len = read_u64_le_at(bytes, pos) as usize;
        pos += 8;
        let backward_off = pos;
        pos += backward_len;
        if pos > bytes.len() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "metric bundle extends past end of mmap",
            ));
        }

        let base = mmap.as_ptr() as usize;
        for (name, off) in [("forward", forward_off), ("backward", backward_off)] {
            let addr = base + off;
            if addr % std::mem::align_of::<u32>() != 0 {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("metric section '{name}' is not u32-aligned"),
                ));
            }
        }

        Ok(MetricBundle {
            mmap,
            forward_off,
            backward_off,
            cch_arc_count,
        })
    }

    /// Return a zero-copy view over the mmap'd metric arrays.
    #[must_use]
    pub fn view(&self) -> MetricView<'_> {
        // SAFETY: open() validated u32 alignment for each offset. The mmap
        // outlives the slices (lifetime tied to &self). The mapped region is
        // read-only and immutable for the lifetime of the Mmap. The alignment
        // check in open() ensures the cast_ptr_alignment requirement is met.
        #[allow(clippy::cast_ptr_alignment)] // alignment verified in open()
        unsafe {
            MetricView {
                forward: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.forward_off).cast::<u32>(),
                    self.cch_arc_count,
                ),
                backward: std::slice::from_raw_parts(
                    self.mmap.as_ptr().add(self.backward_off).cast::<u32>(),
                    self.cch_arc_count,
                ),
            }
        }
    }

    /// Number of CCH arcs.
    #[must_use]
    pub fn cch_arc_count(&self) -> usize {
        self.cch_arc_count
    }
}

// ---------------------------------------------------------------
// Byte-level helpers
// ---------------------------------------------------------------

fn read_u64_le_at(bytes: &[u8], off: usize) -> u64 {
    let mut buf = [0u8; 8];
    buf.copy_from_slice(&bytes[off..off + 8]);
    u64::from_le_bytes(buf)
}

fn read_u32_le_at(bytes: &[u8], off: usize) -> u32 {
    let mut buf = [0u8; 4];
    buf.copy_from_slice(&bytes[off..off + 4]);
    u32::from_le_bytes(buf)
}

// ---------------------------------------------------------------
// Tests
// ---------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opens_bundle_and_down_adjacency_is_consistent() {
        use routingkit_cch::ffi;

        // Build a small path graph: 0→1→2→3→4 (5 nodes, 4 arcs).
        let n: u32 = 5;
        let order: Vec<u32> = (0..n).collect();
        let tail: Vec<u32> = (0..n - 1).collect();
        let head: Vec<u32> = (1..n).collect();

        let cch = unsafe { ffi::cch_new(&order, &tail, &head, |_| {}, false) };
        let cch_ref = cch.as_ref().expect("cch_new returned null");

        // Save the struct bundle into a temp directory.
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().join("tiny.cch-struct");
        let path_str = path.to_str().expect("path is valid UTF-8");

        unsafe { ffi::cch_save_struct(cch_ref, path_str) }
            .expect("cch_save_struct failed");

        // Re-open with our mmap reader.
        let bundle = CchBundle::open(&path).expect("CchBundle::open failed");
        let v = bundle.view();

        let node_count = v.up_first_out.len() - 1;
        assert_eq!(v.down_first_out.len(), node_count + 1);
        assert_eq!(v.down_head.len(), v.up_head.len());
        assert_eq!(v.down_to_up.len(), v.up_head.len());

        // Every down-arc points (via down_to_up) at a valid up-arc.
        for &ua in v.down_to_up {
            assert!(
                (ua as usize) < v.up_head.len(),
                "down_to_up entry {ua} out of range"
            );
        }

        // Transpose property: for each node y, the set of down-neighbours
        // must equal the set of nodes x that have an up-arc whose head is y.
        #[allow(clippy::cast_possible_truncation)] // node_count fits u32 (CCH limit)
        for y in 0..node_count {
            let down_nbrs: std::collections::BTreeSet<u32> = (v.down_first_out[y]
                ..v.down_first_out[y + 1])
                .map(|a| v.down_head[a as usize])
                .collect();
            let y_u32 = y as u32;
            let up_into_y: std::collections::BTreeSet<u32> = (0..node_count as u32)
                .filter(|&x| {
                    (v.up_first_out[x as usize]..v.up_first_out[x as usize + 1])
                        .any(|a| v.up_head[a as usize] == y_u32)
                })
                .collect();
            assert_eq!(down_nbrs, up_into_y, "transpose mismatch at node {y}");
        }
    }
}
